In [22]:
import pandas as pd

In [23]:
import numpy as np

In [24]:
# handling missing data in the dataset

In [25]:
miles = pd.DataFrame({'farthest_run_mi': [50,62,np.nan,100,26,13,31,50]})

In [26]:
miles

,farthest_run_mi
0,50.0
1,62.0
2,NaN
3,100.0
4,26.0
5,13.0
6,31.0
7,50.0


In [27]:
miles.isna().sum()

farthest_run_mi    1
dtype: int64

In [28]:
from sklearn.impute import SimpleImputer

In [29]:
imp_mean = SimpleImputer(strategy = 'mean') # common one for numerical

In [30]:
imp_mean.fit_transform(miles)

array([[ 50.        ],
       [ 62.        ],
       [ 47.42857143],
       [100.        ],
       [ 26.        ],
       [ 13.        ],
       [ 31.        ],
       [ 50.        ]])

In [31]:
imp_median = SimpleImputer(strategy = 'median') # common one for numerical

In [32]:
imp_median.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [33]:
imp_mode = SimpleImputer(strategy = 'most_frequent') # common one for numerical

In [34]:
imp_mode.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [35]:
imp_constant = SimpleImputer(strategy = 'constant', fill_value = 13) # one for numerical

In [36]:
imp_constant.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 13.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [70]:
names = pd.DataFrame({'name' : ['ryan', 'nolan', 'honus', 'wagner', np.nan, 'ruth']}) # one for categorical data

In [38]:
names

,name
0,ryan
1,nolan
2,honus
3,wagner
4,NaN
5,ruth


In [40]:
imp_constant_cat = SimpleImputer(strategy = 'constant', fill_value = 'babe')

In [44]:
imp_constant_cat.fit_transform(names)

array([['ryan'],
       ['nolan'],
       ['honus'],
       ['wagner'],
       ['babe'],
       ['ruth']], dtype=object)

In [45]:
imp_mean_marked = SimpleImputer(strategy = 'mean', add_indicator = True)

In [47]:
imp_mean_marked.fit_transform(miles)

array([[ 50.        ,   0.        ],
       [ 62.        ,   0.        ],
       [ 47.42857143,   1.        ],
       [100.        ,   0.        ],
       [ 26.        ,   0.        ],
       [ 13.        ,   0.        ],
       [ 31.        ,   0.        ],
       [ 50.        ,   0.        ]])

In [60]:
df = pd.read_csv("medical_fixed.csv")

In [61]:
df = df.drop(columns = ["sex", "smoker"])

In [62]:
df

,age,bmi,children,region,charges
0,19,27.900,0,southwest,16884.92400
1,18,33.770,1,southeast,1725.55230
2,28,33.000,3,southeast,4449.46200
3,33,22.705,0,northwest,21984.47061
4,32,28.880,0,northwest,3866.85520
...,...,...,...,...,...
1333,50,30.970,3,northwest,10600.54830
1334,18,31.920,0,northeast,2205.98080
1335,18,36.850,0,southeast,1629.83350
1336,21,25.800,0,southwest,2007.94500


In [53]:
from sklearn.compose import make_column_transformer

In [66]:
ct = make_column_transformer(
    (imp_constant_cat, ["region"]),
    (imp_mean, ['charges']),
    remainder = 'drop'
)

In [67]:
ct.set_output(transform = 'pandas')

,"transformers transformers: list of tuplesList of (name, transformer, columns) tuples specifying thetransformer objects to be applied to subsets of the data.name : str Like in Pipeline and FeatureUnion, this allows the transformer and its parameters to be set using ``set_params`` and searched in grid search.transformer : {'drop', 'passthrough'} or estimator Estimator must support :term:`fit` and :term:`transform`. Special-cased strings 'drop' and 'passthrough' are accepted as well, to indicate to drop the columns or to pass them through untransformed, respectively.columns : str, array-like of str, int, array-like of int, array-like of bool, slice or callable Indexes the data on its second axis. Integers are interpreted as positional columns, while strings can reference DataFrame columns by name. A scalar string or int should be used where ``transformer`` expects X to be a 1d array-like (vector), otherwise a 2d array will be passed to the transformer. A callable is passed the input data `X` and can return any of the above. To select multiple columns by name or dtype, you can use :obj:`make_column_selector`.","[('simpleimputer-1', ...), ('simpleimputer-2', ...)]"
,"remainder remainder: {'drop', 'passthrough'} or estimator, default='drop'By default, only the specified columns in `transformers` aretransformed and combined in the output, and the non-specifiedcolumns are dropped. (default of ``'drop'``).By specifying ``remainder='passthrough'``, all remaining columns thatwere not specified in `transformers`, but present in the data passedto `fit` will be automatically passed through. This subset of columnsis concatenated with the output of the transformers. For dataframes,extra columns not seen during `fit` will be excluded from the outputof `transform`.By setting ``remainder`` to be an estimator, the remainingnon-specified columns will use the ``remainder`` estimator. Theestimator must support :term:`fit` and :term:`transform`.Note that using this feature requires that the DataFrame columnsinput at :term:`fit` and :term:`transform` have identical order.",'drop'
,"sparse_threshold sparse_threshold: float, default=0.3If the output of the different transformers contains sparse matrices,these will be stacked as a sparse matrix if the overall density islower than this value. Use ``sparse_threshold=0`` to always returndense. When the transformed output consists of all dense data, thestacked result will be dense, and this keyword will be ignored.",0.3
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.",None
,"transformer_weights transformer_weights: dict, default=NoneMultiplicative weights for features per transformer. The output of thetransformer is multiplied by these weights. Keys are transformer names,values the weights.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each transformer will beprinted as it is completed.",False
,"verbose_feature_names_out verbose_feature_names_out: bool, str or Callable[[str, str], str], default=True- If True, :meth:`ColumnTransformer.get_feature_names_out` will prefix all feature names with the name of the transformer that generated that feature. It is equivalent to setting `verbose_feature_names_out=""{transformer_name}__{feature_name}""`.- If False, :meth:`ColumnTransformer.get_feature_names_out` will not prefix any feature names and will error if feature names are not unique.- If ``Callable[[str, str], str]``, :meth:`ColumnTransformer.get_feature_names_out` will rename all the features using the name of the transformer. The first argument of the callable is the transformer name and the second argument is the feature name. The returned string will be the new feature name.- If ``str``, it must be a string ready for formatting. The given string will be formatted using two field names: ``transformer_nam

In [68]:
df_pandas = ct.fit_transform(df)

In [69]:
df_pandas

,simpleimputer-1__region,simpleimputer-2__charges
0,southwest,16884.92400
1,southeast,1725.55230
2,southeast,4449.46200
3,northwest,21984.47061
4,northwest,3866.85520
...,...,...
1333,northwest,10600.54830
1334,northeast,2205.98080
1335,southeast,1629.83350
1336,southwest,2007.94500
